apiVersion: v1
kind: Pod
metadata:
  name: temp-pod
spec:
  containers:
  - name: temp-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: model-volume
      mountPath: /model
  volumes:
  - name: model-volume
    persistentVolumeClaim:
      claimName: mnist-model-pvc

